; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.4.1 on Tue Jul 16 2024 15:15:07 GMT+0200 (Doğu Avrupa Standart Saati)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


