; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.4.1 on Tue Jul 16 2024 15:15:08 GMT+0200 (Doğu Avrupa Standart Saati)

